// Generated by Wrangler by running `wrangler types`

interface Env {
	ENVIRONMENT: "production";
	JWT_SECRET: string;
	RESEND_API_KEY: string;
	RESEND_FROM: string;
	ADMIN_EMAIL: string;
	SITE_URL: string;
	CORS_ORIGIN: string;
	IMAGES: R2Bucket;
	DB: D1Database;
}
