-- Demo data for the Influencer Manager (brands + looks + page settings).
-- Idempotent: fixed ids + INSERT OR REPLACE so re-running just refreshes it.

-- ── Page settings singleton ───────────────────────────────────────────────────
INSERT OR REPLACE INTO influencer_page_settings (id, data) VALUES (
  'singleton',
  json('{
    "pageTitle": "All Top Influencers",
    "pageSubtitle": "Discover curated looks, interior inspiration and shoppable styles from top creators.",
    "longContent": "",
    "faqs": [],
    "seoTitle": "Influencer Looks and Products",
    "seoDescription": "Discover shoppable influencer looks, products and interior inspiration.",
    "seoKeywords": "influencer, interior, shoppable looks, home decor"
  }')
);

-- ── Brands ────────────────────────────────────────────────────────────────────
INSERT OR REPLACE INTO influencer_brands (id, username, display_name, data) VALUES
('demo-brand-1', 'sherricalnanhome', 'Sherri Calnan Home', json('{"username":"sherricalnanhome","displayName":"Sherri Calnan Home","name":"Sherri Calnan Home","logo":"https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80","bio":"Coastal, cozy and calm interiors. Shop my favorite looks for a warm neutral home.","createdAt":"2026-07-05T00:00:00.000Z","updatedAt":"2026-07-05T00:00:00.000Z"}')),
('demo-brand-2', 'studiomcgee', 'Studio McGee', json('{"username":"studiomcgee","displayName":"Studio McGee","name":"Studio McGee","logo":"https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80","bio":"Modern, organic and timeless design. Curated pieces to elevate every room.","createdAt":"2026-07-05T00:00:00.000Z","updatedAt":"2026-07-05T00:00:00.000Z"}'));

-- ── Looks ─────────────────────────────────────────────────────────────────────
INSERT OR REPLACE INTO influencer_looks (id, look_id, username, is_published, created_at, data) VALUES
('demo-look-1', 'look-shc-1', 'sherricalnanhome', 1, '2026-07-05T00:00:01.000Z', json('{"lookId":"look-shc-1","username":"sherricalnanhome","title":"Coastal Cozy Bedroom","caption":"Soft linens and natural textures for a calm retreat.","longContent":"<h2>A calm coastal retreat</h2><p>Layered linens, warm wood and woven textures come together for a restful bedroom.</p>","seoTitle":"Coastal Cozy Bedroom Look","seoDescription":"Shop the coastal cozy bedroom look with linen bedding, rattan lighting and natural decor.","heroImage":"https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80","products":[{"id":"p1","name":"Washed Linen Duvet Set","image":"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=500&q=80","price":"€ 129,00","link":"https://www.example.com/linen-duvet"},{"id":"p2","name":"Rattan Table Lamp","image":"https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=500&q=80","price":"€ 59,00","link":"https://www.example.com/rattan-lamp"},{"id":"p3","name":"Ceramic Vase Set","image":"https://images.unsplash.com/photo-1578500494198-246f612d3b3d?auto=format&fit=crop&w=500&q=80","price":"€ 39,00","link":"https://www.example.com/ceramic-vase"}],"faqs":[{"question":"How do I buy the products from this look?","answer":"Click on a product and you will be taken directly to the partner shop."}],"similarCategories":["Schlafzimmer","Dekoration"],"tags":["coastal","cozy","neutral"],"isPublished":true,"createdAt":"2026-07-05T00:00:01.000Z","updatedAt":"2026-07-05T00:00:01.000Z"}')),
('demo-look-2', 'look-shc-2', 'sherricalnanhome', 1, '2026-07-05T00:00:02.000Z', json('{"lookId":"look-shc-2","username":"sherricalnanhome","title":"Warm Neutral Living Room","caption":"A boucle sofa and oak accents for an inviting space.","longContent":"<h2>Warm and inviting</h2><p>A soft boucle sofa paired with oak and wool creates a welcoming living room.</p>","seoTitle":"Warm Neutral Living Room Look","seoDescription":"Shop the warm neutral living room with a boucle sofa, oak coffee table and wool rug.","heroImage":"https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=900&q=80","products":[{"id":"p1","name":"Boucle 3-Seater Sofa","image":"https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?auto=format&fit=crop&w=500&q=80","price":"€ 899,00","link":"https://www.example.com/boucle-sofa"},{"id":"p2","name":"Oak Coffee Table","image":"https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&w=500&q=80","price":"€ 249,00","link":"https://www.example.com/oak-table"},{"id":"p3","name":"Handwoven Wool Rug","image":"https://images.unsplash.com/photo-1600166898405-da9535204843?auto=format&fit=crop&w=500&q=80","price":"€ 179,00","link":"https://www.example.com/wool-rug"}],"faqs":[{"question":"Are the prices up to date?","answer":"Prices can change at any time. Please check with the respective retailer."}],"similarCategories":["Wohnzimmer","Dekoration"],"tags":["neutral","warm","living"],"isPublished":true,"createdAt":"2026-07-05T00:00:02.000Z","updatedAt":"2026-07-05T00:00:02.000Z"}')),
('demo-look-3', 'look-smcg-1', 'studiomcgee', 1, '2026-07-05T00:00:03.000Z', json('{"lookId":"look-smcg-1","username":"studiomcgee","title":"Modern Minimal Kitchen","caption":"Clean lines, warm wood and statement lighting.","longContent":"<h2>Modern minimal</h2><p>Warm wood stools and a sculptural pendant bring balance to a minimal kitchen.</p>","seoTitle":"Modern Minimal Kitchen Look","seoDescription":"Shop the modern minimal kitchen with counter stools and a statement pendant light.","heroImage":"https://images.unsplash.com/photo-1556909212-d5b604d0c90d?auto=format&fit=crop&w=900&q=80","products":[{"id":"p1","name":"Oak Counter Stool","image":"https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=500&q=80","price":"€ 119,00","link":"https://www.example.com/counter-stool"},{"id":"p2","name":"Sculptural Pendant Light","image":"https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?auto=format&fit=crop&w=500&q=80","price":"€ 149,00","link":"https://www.example.com/pendant-light"}],"faqs":[{"question":"How do I buy the products from this look?","answer":"Click on a product and you will be taken directly to the partner shop."}],"similarCategories":["Küche","Beleuchtung"],"tags":["modern","minimal","kitchen"],"isPublished":true,"createdAt":"2026-07-05T00:00:03.000Z","updatedAt":"2026-07-05T00:00:03.000Z"}')),
('demo-look-4', 'look-smcg-2', 'studiomcgee', 1, '2026-07-05T00:00:04.000Z', json('{"lookId":"look-smcg-2","username":"studiomcgee","title":"Organic Modern Bedroom","caption":"An upholstered bed and warm woods for a serene space.","longContent":"<h2>Organic modern</h2><p>An upholstered bed grounded by warm wood nightstands creates a serene bedroom.</p>","seoTitle":"Organic Modern Bedroom Look","seoDescription":"Shop the organic modern bedroom with an upholstered bed and wood nightstand.","heroImage":"https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=900&q=80","products":[{"id":"p1","name":"Upholstered Platform Bed","image":"https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=500&q=80","price":"€ 749,00","link":"https://www.example.com/upholstered-bed"},{"id":"p2","name":"Wood Nightstand","image":"https://images.unsplash.com/photo-1532372320572-cda25653a26d?auto=format&fit=crop&w=500&q=80","price":"€ 189,00","link":"https://www.example.com/nightstand"}],"faqs":[{"question":"Are the prices up to date?","answer":"Prices can change at any time. Please check with the respective retailer."}],"similarCategories":["Schlafzimmer"],"tags":["organic","modern","bedroom"],"isPublished":true,"createdAt":"2026-07-05T00:00:04.000Z","updatedAt":"2026-07-05T00:00:04.000Z"}'));
